---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synatainer.fullname" . }}-tokens
  labels:
    {{- include "synatainer.labels" . | nindent 4 }}
data:
  pgpassword: {{ include "synatainer.pgpassword" . | b64enc }}
  mxtoken: {{ include "synatainer.mxtoken" . | b64enc }}
{{- with .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synatainer.fullname" $ }}
  labels:
    {{- include "synatainer.labels" $ | nindent 4 }}
data:
{{-   range $key, $val := . }}
  {{ $key }}: {{ $val | toString | b64enc }}
{{-   end -}}
{{- end }}
