{{- $adminPassword := include "lemmy.adminpassword" . -}}
{{- $pictrsApikey := include "lemmy.pictrsapikey" . -}}
{{- $config := dict
  "database"
    (dict
      "user" (include "lemmy.postgresql.username" .)
      "password" (include "lemmy.postgresql.password" .)
      "host" (include "lemmy.postgresql.host" .)
      "port" (include "lemmy.postgresql.port" . | int)
      "database" (include "lemmy.postgresql.database" .)
      "pool_size" (.Values.postgresql.poolSize | default 10)
    )
  "pictrs"
    (dict
      "url" (printf "http://%s:%d" (include "lemmy.pictrsname" .) (int .Values.pictrs.service.port))
      "api_key" (.Values.pictrs.apikey | default $pictrsApikey)
    )
  "email"
    (dict
      "smtp_server" .Values.smtp.server
      "smtp_login" .Values.smtp.username
      "smtp_password" .Values.smtp.password
      "smtp_from_address" .Values.smtp.from
      "tls_type" .Values.smtp.tls
    )
  "setup"
    (dict
      "admin_username" (.Values.admin.username | default "lemmy")
      "admin_password" (.Values.admin.password | default $adminPassword)
      "admin_email" .Values.admin.email
      "site_name" .Values.config.siteName
    )
  "hostname" .Values.serverName
  "bind" "0.0.0.0"
  "port" 8536
  "tls_enabled" (.Values.config.tls | default true)
-}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lemmy.fullname" . }}
  labels:
    {{- include "lemmy.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
{{- if not .Values.admin.existingSecret }}
  admin_password: {{ $adminPassword | b64enc }}
{{- end }}
{{- if not .Values.pictrs.existingSecret }}
  pictrs_apikey: {{ $pictrsApikey | b64enc }}
{{- end }}
  config.hjson: {{ $config | toPrettyJson | b64enc }}
