---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synatainer.fullname" . }}
  labels:
    {{- include "synatainer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "synatainer.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "synatainer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - command:
            - sh
            - -c
            - |
              cp /tmp/mxtoken /conf/
              cp /tmp/pgpassword /conf/
              exec /entrypoint.sh
          name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: {{ include "synatainer.fullname" . }}
          {{- if .Values.extraSecrets }}
            - secretRef:
                name: {{ include "synatainer.fullname" . }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: emptydir
              mountPath: /conf
            - name: tokens
              mountPath: /tmp/pgpassword
              subPath: pgpassword
            - name: tokens
              mountPath: /tmp/mxtoken
              subPath: mxtoken
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tokens
          secret:
            secretName: {{ include "synatainer.fullname" . }}-tokens
            defaultMode: 0600
        - name: emptydir
          emptyDir: {}
