{{- $port := .Values.frontendPort | default 8008 -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "radosgw.fullname" . }}
  labels:
    {{ include "radosgw.labels" . | nindent 4 }}
data:
  ceph.conf: |+
    [global]
    mon_host = {{ include "helm-toolkit.utils.joinListWithComma" .Values.monHosts }}
    rgw dns name = {{ .Values.dnsName }}
{{- if eq .Values.frontend "beast" }}
    rgw frontends = beast endpoint=0.0.0.0 port={{ $port }}
{{- else if eq .Values.frontend "civetweb" }}
    rgw frontends = civetweb port={{ $port }}
{{- end }}
{{- if .Values.extraCephConf }}

    {{ .Values.extraCephConf | nindent 4 }}
{{- end }}
