---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radosgw.fullname" . }}
  labels:
    {{ include "radosgw.labels" . | nindent 4 }}
data:
  client.admin.keyring: {{ include "radosgw.keyringFile" (dict "Client" "admin" "Key" .Values.adminKey) | b64enc }}
  bootstrap-rgw.keyring: {{ include "radosgw.keyringFile" (dict "Client" "bootstrap-rgw" "Key" .Values.bootstrapKey) | b64enc }}
