apiVersion: v1
kind: Service
metadata:
  name: {{ include "radosgw.fullname" . }}
  labels:
    {{ include "radosgw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "radosgw.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
