{{- if (and (not .Values.config.persistence.existingClaim) .Values.config.persistence.enabled) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "peertube.fullname" . }}
  labels:
    {{- include "peertube.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- .Values.config.persistence.accessModes | default (list "ReadWriteOnce") | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.config.persistence.size | quote }}
  {{- if .Values.config.persistence.storageClass }}
  {{- if (eq "-" .Values.config.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.config.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
