apiVersion: v1
kind: Service
metadata:
  name: {{ include "peertube.fullname" . }}
  labels:
    {{- include "peertube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.rtmpPort }}
      targetPort: rtmp
      protocol: TCP
      name: rtmp
  selector:
    {{- include "peertube.selectorLabels" . | nindent 4 }}
