apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lemmy.pictrsname" . }}
  labels:
    {{- include "lemmy.labels" . | nindent 4 }}
    app.kubernetes.io/component: pictrs
data:
  PICTRS__REPO__PATH: {{ "/mnt/database" | b64enc }}
  PICTRS__STORE__TYPE: {{ .Values.pictrs.storage.method | b64enc }}

{{- if (eq .Values.pictrs.storage.method "object_storage") }}
  {{- $s3 := .Values.pictrs.storage.objectStorage }}
  {{- if $s3.endpoint }}
  PICTRS__STORE__ENDPOINT: {{ $s3.endpoint | b64enc }}
  {{- end }}
  PICTRS__STORE__USE_PATH_STYLE: {{ $s3.usePathStyle | default false | toString | b64enc }}
  PICTRS__STORE__BUCKET_NAME: {{ required "S3 bucket must be specified" $s3.bucketName | b64enc }}
  PICTRS__STORE__REGION: {{ required "S3 region must be specified" $s3.region | b64enc }}
  {{- if not $s3.existingSecret }}
  PICTRS__STORE__ACCESS_KEY: {{ required "S3 access key must be specified" $s3.accessKey | b64enc }}
  PICTRS__STORE__SECRET_KEY: {{ required "S3 secret key must be specified" $s3.secretKey | b64enc }}
  {{- end }}
  {{- if $s3.sessionToken }}
  PICTRS__STORE__SESSION_TOKEN: {{ $s3.sessionToken | b64enc }}
  {{- end }}
{{- else }}
  PICTRS__STORE__PATH: {{ "/mnt/media" | b64enc }}
{{- end }}
